version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongo:27017/to-do-list-app
      - SESSION_SECRET=sEw/9+j7n/R3rYNmupAHvZORfSjhFD6Fn7M6jImLmKE=
    depends_on:
      - mongo

  todo-service:
    build:
      context: ./todo-service
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=mongodb://mongo:27017/to-do-list-app
      - SESSION_SECRET=sEw/9+j7n/R3rYNmupAHvZORfSjhFD6Fn7M6jImLmKE=
    depends_on:
      - mongo

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "8083:8083"
    environment:
      - MONGO_URI=mongodb://mongo:27017/to-do-list-app
      - SESSION_SECRET=sEw/9+j7n/R3rYNmupAHvZORfSjhFD6Fn7M6jImLmKE=
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
